### ISSUE TITLE
Platform Automation Resources - request to update product_version

### ISSUE THREAD

**Issue by TheKoguryo** [pivotal/docs-platform-automation#28]
**URL or GitHub link to the page where you're having the issue**
https://docs.pivotal.io/platform-automation/v4.3/pipelines/resources.html#platform-automation-resources

```yaml
- name: platform-automation-pivnet
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: platform-automation
    product_version: 2\.(.*)
    sort_by: semver
```

**Is your request for a change or addition to content related to a problem? If so, please describe.**
2.x.x version does not exist in pivnet. And so product_version: 2\.(.*) makes that the concourse downloads 4.2.3 version currently.
But 4.2.3 version of platform-automation-tasks does not have prepare-tasks-with-secrets.yml and so file not found error is occurred.

**Describe the solution you'd like**
I hope to change product_version from 2\.(.*) to 4\.(.*). After this change, it works.
